### ISSUE TITLE
Hide Cursor not working

### ISSUE THREAD

**Issue by ghost** [o-marshmallow/PocketCHIP-pocket-home#10]
The "Hide Cursor" option in the advanced settings isn't working while using the default terminal emulator: "vala-terminal". I've also tested with the "st" terminal emulator, the cursor shows even though "Not Visible" is selected.

**Comment by o-marshmallow** [comment]
Hello @itpaul ,

It's "normal", I mean, this option is for the home only, other applciations have the right to show cursor or not. I added this option because before, if you plugged a mouse to your PocketCHIP, you couldn't see the cursor, so it was not usable. I think hiding the cursor can be totally hidable but throught `Awesome`config file

**Comment by ghost** [comment]
Ok, thanks @o-marshmallow!
