### ISSUE TITLE
apt-get upgrade -> downgrades pocket-home back to orginal version

### ISSUE THREAD

**Issue by AndrewHumphreys** [o-marshmallow/PocketCHIP-pocket-home#11]
Ever since I have flashed my pocket chip to v4.4 'sudo apt-get upgrade' actually downgrades pocket-home back to the orginal version.

My current work around is to delete .pocket-home/.version & re-install. Surprisingly all my settings/icons haven't changed.

**Comment by o-marshmallow** [comment]
Hello @AndrewHumphreys  !

This problem has been reported in the official forum, a member named **processedsanity** gave a solution:
after installing the last version (this custom one), type:
`sudo apt-mark hold pocket-home`
This will avoid replacing the pocket-home when upgrading

The icons haven't changed because the file containing the configuration is also located in the folder `~/.pocket-home`which is not used/delete by the original pocket-home
